site_name: Senteon Documentation
theme: readthedocs
site_author: Henry Zhang
repo_name: GitHub
docs_dir: 'docs'
site_dir: 'site'
use_directory_urls: true
nav:
    - 'Home': 'index.md'
    - 'Endpoint Configuration': 'endpointconfiguration.md'
    - 'Alerts': 'alerts.md'
    - 'Reports': 'reports.md'
    - 'Settings': 'settings.md'
    - 'Users and Permissions': 'usersandpermissions.md'
    - 'Updates' : 'updates.md'
    - 'Technical Details': 'technicaldetails.md'
markdown_extensions:
  - attr_list
